# Top Ranking Group By Request
ranking_count = 30

# Top Slow Requests
slow_count = 37

# Show Standard Deviation column
show_stddev = true

# Show HTTP Status Code columns
show_status_code = true

# Show HTTP Response Bytes columns
show_bytes = true

# Percentiles
percentiles = [ 99.9 ]

# for Nginx($request_time)
scale = 0
effective_digit = 3

# for Apache(%D) and Varnishncsa(%D)
#scale = -6
#effective_digit = 6

# for Rack(Rack::CommonLogger)
#scale = 0
#effective_digit = 4


# combined + duration
# Nginx example: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'
# Apache example: "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D"
# H2O example: "%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\" %{duration}x"
# Varnishncsa example: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %D'
log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" ([0-9.]+) ([0-9.]+)$'

request_index = 5
status_index = 6
bytes_index = 7
duration_index = 11

# Rack example: use Rack::CommonLogger, Logger.new("/tmp/app.log")
#log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) ([0-9.]+)$'
#request_index = 5
#status_index = 6
#bytes_index = 7
#duration_index = 8

# You can aggregate requests by regular expression
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
[[bundle]]
regexp = '^(GET|HEAD) /api/chair/[0-9]+'
name = "get /api/chair/:id"

[[bundle]]
regexp = '^(GET|HEAD) /api/chair/search'
name = "get /api/chair/search"

[[bundle]]
regexp = '^(GET|HEAD) /api/chair/low_priced'
name = "get /api/chair/low_priced"

[[bundle]]
regexp = '^(GET|HEAD) /api/chair/search/condition'
name = "get /api/chair/search/condition"

[[bundle]]
regexp = '^POST /api/chair/buy/[0-9]+'
name = "post /api/chair/buy/:id"

[[bundle]]
regexp = '^(GET|HEAD) /api/estate/[0-9]+'
name = "get /api/estate/:id"

[[bundle]]
regexp = '^(GET|HEAD) /api/estate/search'
name = "get /api/estate/search"

[[bundle]]
regexp = '^(GET|HEAD) /api/estate/low_priced'
name = "get /api/estate/low_priced"

[[bundle]]
regexp = '^POST /api/estate/req_doc/[0-9]+'
name = "post /api/estate/req_doc/[0-9]+"

[[bundle]]
regexp = '^(GET|HEAD) /api/estate/search/condition'
name = "get /api/estate/search/condition"

[[bundle]]
regexp = '^(GET|HEAD) /api/recommended_estate/[0-9]+'
name = "get /api/recommended_estate/:id"

[[bundle]]
regexp = '^(GET|HEAD) /images/'
name = "get /images/*"

[[bundle]]
regexp = '^(GET|HEAD) /_next/'
name = "get /_next/*"

# You can replace the part of urls which matched to your regular expressions.
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
#[[replace]]
#regexp = '/[0-9]+/'
#replace = '/<num>/'
#
#[[replace]]
#regexp = '/[0-9]+\s'
#replace = '/<num> '
#
#[[replace]]
#regexp = '=[0-9]+&'
#replace = '=<num>&'
#
#[[replace]]
#regexp = '=[0-9]+\s'
#replace = '=<num> '
